### PR TITLE
Illustrator CC 2014.1 (18.1) host adapter, for HTML extensions.

### PR DESCRIPTION
**Pull request by timothybrandspencer**

### CODE REVIEW

**Comment by schoudry** [comment]
@timothybrandspencer have verified it (2014 AIHostAdapter.aip plugin) works in 2018 illustrator as-is.. however

i have a usecase to process and write something to xmp before saving the doc

`AIEventAdapter.getInstance().addEventListener(AIEvent.DOCUMENT_WRITE_PREPROCESS, extractAndWriteBeforeSave);`

using the above call i could write data to xmp but save doesn't wait until the data is written, so document becomes dirty again (shows asterisk)..

 how can we tell save action to wait until the processing is done using AIEventAdapter?

**Comment by rahul-dutt-sharma** [comment]
@schoudry where did u find the source for ai_host_adapter, cs_host_adapter? why did we close the PR without including these files in the main repo, but we included the .aip plugin. Do we not need these files? My plugins do not work unless it include these files

**Comment by ErinFinnegan** [comment]
Hi there!

We did upload a new `ai_host_adapter` here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_9.x/Host%20adapters/Illustrator/AIHostAdapter

I don't have any information on the `cs_host_adapter` file... but the "CS" makes me think it's for use with Creative Suite (CS 6 or earlier), which is no longer supported.

**Comment by rahul-dutt-sharma** [comment]
These are the .aip plugins, which I am very thankful were uploaded as these can be notrarized

The files I were talking about were the js files which were in that PR

They have content from adove


Here is the top level code

**
* AIEventAdapter provides APIs for registering and unregistering event
* listeners for Illustrator events. It requires the AIHostAdapter native
* plugin to be installed in the host application in order for its method
* calls to have any effect.
*
* Use the addEventListener and removeEventListener
* methods to add and remove event listeners for Illustrator events.
*
* The AIEvent class provides a set of constants representing
* the events supported.
* For example, to listen for the ART_SELECTION_CHANGED event, use:
*
* AIEventAdapter.getInstance().addEventListener(AIEvent.ART_SELECTION_CHANGED, listener);
*
* where listener is a method with the following signature:
*
* function listener(event:AIEvent)
*
*/
function AIEventAdapter()

**Pull request closed without merging**
