### PR TITLE
Updated Cef-Client for Debugging

### PR DESCRIPTION
**Pull request by rushilmahajan-adobe**
Spotify CEFClient for Debugging

### CODE REVIEW

**Comment by thirdknife** [comment]
What Adobe application version are you using? maybe this only works with latest versions.

**Comment by rushilmahajan-adobe** [comment]
@mehanig , Can you specify which version of CEP or Adobe (Application's version) you are using?

**Comment by mehanig** [comment]
@rushilmahajan-adobe  Sure, it's 
image
on OSX

**Comment by rushilmahajan-adobe** [comment]
Thanks @mehanig for your input, we have updated put CEF Client.

**Comment by rushilmahajan-adobe** [comment]
Thanks, @mehanig, and @thirdknife  for your input, we have update the CEF Client.

**Comment by mehanig** [comment]
Thank you for a quick fix, I double checked the new version, looks pretty much stable on my projects.

**Pull request merged**
